capstone-kelompok-7/frontend-disappear

src/components/table/table.jsx
src/styles/table.css

perubahan pada warna header dan border table

feat: mengganti warna header dan border radius table

---

src/components/sidebar/sidebar.jsx
src/pages/order/order.jsx
src/pages/pelanggan/pelanggan.jsx
src/routes/router.jsx
src/styles/order/order.css

membuat halaman order

---

src/components/sidebar/sidebar.jsx
src/pages/payment/confirmPayment.jsx
src/pages/payment/indexPayment.jsx
src/routes/router.jsx

Index Payment
Confirm Payment baru Layout dan Breadcrumbs

Payment Page

---

src/pages/order/detailOrder.jsx
src/pages/order/order.jsx
src/routes/router.jsx
tailwind.config.js

slicing detail order page

---

src/components/sidebar/sidebar.jsx
src/components/ui/input.jsx
src/pages/carousel/index.jsx
src/pages/carousel/popUp.jsx
src/routes/router.jsx

feat: create page carousel

---

src/components/layout.jsx
src/pages/dashboard/dashboard.jsx

refactor: fixing minor bug layout and centering icon section

---

src/components/button.jsx
src/components/ui/input.jsx
src/components/ui/textarea.jsx
src/pages/products/createEditProducts/createEditProducts.jsx
src/pages/products/detailProducts/detailProducts.jsx
src/pages/products/indexProducts.jsx
src/utils/api/products/api.js

https://github.com/capstone-kelompok-7/frontend-disappear/assets/92997581/50555d0a-25fb-405b-8dfb-6de0d5f97beb
ini sudah kubuat integrasi create products tapi ada beberapa file yg butuh penyesuaian kayak button, ui/input, ui/textarea.
untuk button typenya kujadiin props, untuk ui/input dan ui/textarea itu kutambahin props register dan name untuk penyesuaian rhf, zod, dan @hookform/resolvers

feat: create products without category and image

---

src/pages/payment/confirmPayment.jsx
src/pages/payment/indexPayment.jsx
src/routes/router.jsx
src/utils/api/paymentAndOrder/api.js
src/utils/formatter/formatStatusColor.js

feat: integration getallorder at payment page and getorder by id at confirm payment Page

---

src/components/cardartikel/cardArtikel.jsx
src/components/texteditor/tipTap.jsx
src/pages/Artikel/createNews.jsx
src/pages/Artikel/editNews.jsx
src/pages/Artikel/indexNews.jsx
src/styles/titap.css
src/utils/api/artikel/api.js
src/utils/api/artikel/schemaArtikel.js

Artikel news2

---

src/components/dashboard/dashboardIcon.jsx
src/components/table/table.jsx
src/pages/dashboard/dashboard.jsx
src/styles/table.css
src/utils/api/dashboard/api.js

feat: implement get api in Dashboard Page

---

src/components/table/table.jsx
src/pages/dashboard/dashboard.jsx
src/styles/table.css

refactor: styling table 

---

src/pages/carousel/index.jsx
src/utils/api/carousel/api.js
tailwind.config.js

feat: api implementation in Carousel page to get all data

---

package-lock.json
package.json
src/pages/ulasan/indexUlasan.jsx

Feature : Search Review

---

src/pages/dashboard/dashboard.jsx
src/pages/login/LoginPage.jsx

refactor: adding condition when payment_status Gagal

---

src/pages/landingpage/landingpage.jsx
src/styles/landingpage/landingpage.css
src/utils/api/landingpage/api.js

get landing page and get reviews

Landingpage integration

---

src/pages/ulasan/detailUlasan/detailUlasan.jsx
src/pages/ulasan/indexUlasan.jsx
src/utils/api/ulasan/api.js

Halaman Ulasan

---

src/pages/carousel/caraoselPage.jsx
src/pages/carousel/caraouselModal.jsx
src/utils/api/carousel/schema.js

refactor: change schema for image optional for update by setting default value

---

src/pages/voucherPage/voucherIndex.jsx

add format number and add dependencies toast

feat: add format number

---

src/pages/order/detailOrder.jsx
src/pages/order/order.jsx
src/routes/router.jsx

Get All & Get Detail Order

---

src/pages/payment/indexPayment.jsx

Implemented filters for transaction status and date ranges on the payment

---

src/pages/order/detailOrder.jsx
src/pages/order/order.jsx
src/utils/api/paymentAndOrder/api.js
src/utils/api/paymentAndOrder/schema.js

add integration order & detail order

---

src/pages/pelanggan/pelanggan.jsx
src/pages/pelanggan/pelangganDetail.jsx
src/styles/pelanggan/pelanggan.css

integration pelanggan page

---

src/pages/voucherPage/createEditVoucher.jsx
src/pages/voucherPage/voucherIndex.jsx

- adding id props
- add id props

Filter Table Voucher Page

---

src/pages/carousel/caraoselPage.jsx
src/pages/carousel/caraouselModal.jsx

feat: error handling search params when data not found

---

src/pages/ulasan/detailUlasan/detailUlasan.jsx
src/pages/ulasan/indexUlasan.jsx

Menambahkan limit gambar yang di tampilkan

Fix detail reviews

---

src/pages/payment/confirmPayment.jsx

fix: fix when image not found
